language: android


android:
    components:

      # Tools
      - tools
      - platform-tools
      - build-tools-23.0.2
      - android-23

      # Extras
      - extra-android-support
      - extra-android-m2repository
      - extra-google-m2repository
      - addon-google_apis-google-23
      - extra-google-google_play_services

      # Emulator
      - sys-img-android-23-armeabi-v7a



script:
  - ./gradlew build test
